#use: mkmf -t Makefile.template -p nbo.exe
#to generate a proper makefile

MKLROOT=/public1/soft/intel/2020/compilers_and_libraries_2020.4.304/linux/mkl/include/intel64/lp64/


LD=ifort
FC=ifort
FFLAGS= -I$(MKLROOT) -qopenmp 
LDFLAGS=-L$(MKLROOT) -qopenmp -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lpthread -lm -I$(MKLROOT) -mkl=sequential
